using System.Text.Json.Serialization;
using Vimeo.Core.Enum;

namespace Vimeo.Models.Enums;

/// <summary>
/// The origin of the audio track.
/// <para>
/// Option descriptions:
///  * <c>ai_generated</c> - The audio track is generated by AI.
///  * <c>user_uploaded</c> - The audio track is uploaded by a user.
///  * <c>user_uploaded_and_ai_generated</c> - The audio track is uploaded by a user and contains AI content.
/// </para>
/// </summary>
[JsonConverter(typeof(StringEnumConverter<Provenance2>))]
public sealed record Provenance2 : StringEnum<Provenance2>
{
    private Provenance2(string value) : base(value)
    {
    }

    public static readonly Provenance2 AiGenerated = new("ai_generated");

    public static readonly Provenance2 UserUploaded = new("user_uploaded");

    public static readonly Provenance2 UserUploadedAndAiGenerated = new("user_uploaded_and_ai_generated");

    public static Provenance2 FromValue(string value) => FromValueCore(value);
}
