using System.Text.Json.Serialization;
using Vimeo.Core.Enum;

namespace Vimeo.Models.Enums;

/// <summary>
/// The origin of the audio track.
/// <para>
/// Option descriptions:
///  * <c>ai_generated</c> - The audio track is generated by AI.
///  * <c>user_uploaded</c> - The audio track is uploaded by a user.
///  * <c>user_uploaded_and_ai_generated</c> - The audio track is uploaded by a user and contains AI-generated content.
/// </para>
/// </summary>
[JsonConverter(typeof(StringEnumConverter<Provenance>))]
public sealed record Provenance : StringEnum<Provenance>
{
    private Provenance(string value) : base(value)
    {
    }

    public static readonly Provenance AiGenerated = new("ai_generated");

    public static readonly Provenance UserUploaded = new("user_uploaded");

    public static readonly Provenance UserUploadedAndAiGenerated = new("user_uploaded_and_ai_generated");

    public static Provenance FromValue(string value) => FromValueCore(value);
}
