using System.Text.Json.Serialization;
using Vimeo.Core.Enum;

namespace Vimeo.Models.Enums;

/// <summary>
/// The initial privacy of the videos generated by streaming to the event as well as the embed privacy of the entire collection.
/// <para>
/// Option descriptions:
///  * <c>anybody</c> - Anyone can access the event. This privacy setting appears as <c>Public</c> on the Vimeo front end.
///  * <c>embed_only</c> - The event doesn't appear on Vimeo, but it can be embedded on other sites.
///  * <c>nobody</c> - No one except the owner can access the event. This privacy setting appears as <c>Private</c> on the Vimeo front end.
///  * <c>password</c> - Only those with the password can access the event.
///  * <c>team</c> - Anyone on this team can access the event. This privacy setting appears as <c>Company only</c> on the Vimeo front end.
///  * <c>unlisted</c> - Only those with the private link can access the event.
/// </para>
/// </summary>
[JsonConverter(typeof(StringEnumConverter<View9>))]
public sealed record View9 : StringEnum<View9>
{
    private View9(string value) : base(value)
    {
    }

    public static readonly View9 Anybody = new("anybody");

    public static readonly View9 EmbedOnly = new("embed_only");

    public static readonly View9 Nobody = new("nobody");

    public static readonly View9 Password = new("password");

    public static readonly View9 Team = new("team");

    public static readonly View9 Unlisted = new("unlisted");

    public static View9 FromValue(string value) => FromValueCore(value);
}
