using System.Collections.Generic;
using System.Text.Json.Serialization;
using VimeoApi.Models.Enums;

namespace VimeoApi.Models;

public record AlternateAudioTrack
{
    /// <summary>
    /// Whether the audio track is enabled.
    /// </summary>
    [JsonPropertyName("active")]
    public required bool Active { get; init; }

    /// <summary>
    /// The downloads that are available for the audio track.
    /// </summary>
    [JsonPropertyName("download")]
    public required IReadOnlyList<Download1> Download { get; init; }

    /// <summary>
    /// The language of the audio track.
    /// </summary>
    [JsonPropertyName("language")]
    public required Language2 Language { get; init; }

    /// <summary>
    /// The origin of the audio track.
    /// <para>
    /// Option descriptions:
    ///  * <c>ai_generated</c> - The audio track is generated by AI.
    ///  * <c>user_uploaded</c> - The audio track is uploaded by a user.
    ///  * <c>user_uploaded_and_ai_generated</c> - The audio track is uploaded by a user and contains AI-generated content.
    /// </para>
    /// </summary>
    [JsonPropertyName("provenance")]
    public required Provenance Provenance { get; init; }

    /// <summary>
    /// The quota parameters for the audio tracks available for this version.
    /// </summary>
    [JsonPropertyName("quota")]
    public required Quota Quota { get; init; }

    /// <summary>
    /// The transcode information for the audio track.
    /// </summary>
    [JsonPropertyName("transcode")]
    public required Transcode1 Transcode { get; init; }

    /// <summary>
    /// The type of audio track.
    /// <para>
    /// Option descriptions:
    ///  * <c>commentary</c> - The audio track is a commentary.
    ///  * <c>descriptive</c> - The audio track is descriptive for accessibility.
    ///  * <c>main</c> - The audio track is dubbed audio.
    ///  * <c>unknown</c> - The audio track category is unknown.
    /// </para>
    /// </summary>
    [JsonPropertyName("type")]
    public required Type11 Type { get; init; }

    /// <summary>
    /// The upload information for the audio track.
    /// </summary>
    [JsonPropertyName("upload")]
    public required object Upload { get; init; }

    /// <summary>
    /// The audio track's canonical relative URI.
    /// </summary>
    [JsonPropertyName("uri")]
    public required string Uri { get; init; }
}
