using System.Text.Json.Serialization;
using VimeoApi.Core.Models;

namespace VimeoApi.Models;

/// <summary>
/// The embed settings of the event and the videos generated by streaming to this event.
/// </summary>
public record Embed9
{
    /// <summary>
    /// Whether playback starts automatically on load.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("autoplay")]
    public bool? Autoplay { get; init; }

    /// <summary>
    /// The hexadecimal color code for the main color of the embed player.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("color")]
    public string? Color { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("logos")]
    public Logos4? Logos { get; init; }

    /// <summary>
    /// Whether the playlist should start from the beginning again after reaching the end of the last video.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("loop")]
    public bool? Loop { get; init; }

    /// <summary>
    /// Whether to show the playlist controls on the embed player.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("playlist")]
    public bool? Playlist { get; init; }

    /// <summary>
    /// Whether to show the event schedule on the embed player.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("schedule")]
    public bool? Schedule { get; init; }

    /// <summary>
    /// Whether the embed player should use (<c>true</c>) or ignore (<c>false</c>) the <b>embed.color</b> value.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("use_color")]
    public bool? UseColor { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
