using System.Collections.Generic;
using System.Text.Json.Serialization;
using VimeoApi.Models.Enums;

namespace VimeoApi.Models;

public record MeLiveEventsRequest2
{
    /// <summary>
    /// Whether automated closed captions are enabled for the event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("auto_cc_enabled")]
    public bool? AutoCcEnabled { get; init; }

    /// <summary>
    /// A comma-separated list of keywords for enhancing the speech detection of automated closed captions.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("auto_cc_keywords")]
    public string? AutoCcKeywords { get; init; }

    /// <summary>
    /// The language of the automated closed captions.
    /// <para>
    /// Option descriptions:
    ///  * <c>de-DE</c> - The language is German.
    ///  * <c>en-US</c> - The language is English.
    ///  * <c>es-ES</c> - The language is Spanish.
    ///  * <c>fr-FR</c> - The language is French.
    ///  * <c>pt-BR</c> - The language is Portuguese.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("auto_cc_language")]
    public AutoCcLanguage2? AutoCcLanguage { get; init; }

    /// <summary>
    /// Whether the title for the next video in the event is generated based on the time of the stream and the <b>title</b> field of the event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("automatically_title_stream")]
    public bool? AutomaticallyTitleStream { get; init; }

    /// <summary>
    /// Whether to display the live chat client on the Vimeo event page.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("chat_enabled")]
    public bool? ChatEnabled { get; init; }

    /// <summary>
    /// A list of values describing the content in this event. To return the list of all possible content rating values, use the <see href="https://developer.vimeo.com/api/reference/videos#get_content_ratings"><c>/contentratings</c></see> endpoint.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("content_rating")]
    public IReadOnlyList<string>? ContentRating { get; init; }

    /// <summary>
    /// Whether the feature for disabling auto-archiving is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("disable_auto_archiving")]
    public bool? DisableAutoArchiving { get; init; }

    /// <summary>
    /// Whether the DVR feature is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("dvr")]
    public bool? Dvr { get; init; }

    /// <summary>
    /// The embed settings of the event and the videos generated by streaming to this event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("embed")]
    public Embed9? Embed { get; init; }

    /// <summary>
    /// The settings for the interaction tools.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("interaction_tools_settings")]
    public InteractionToolsSettings? InteractionToolsSettings { get; init; }

    /// <summary>
    /// The navbar logo configuration of the event landing page.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("landing_page_logo")]
    public LandingPageLogo2? LandingPageLogo { get; init; }

    /// <summary>
    /// The type of stream delay on the viewer side.
    /// <para>
    /// Option descriptions:
    ///  * <c>fail-safe</c> - The latency is in the failsafe range, with a delay of 60-75 seconds.
    ///  * <c>low</c> - The latency is low, with a delay of 5-7 seconds.
    ///  * <c>standard</c> - The latency is standard, with a delay of 15-20 seconds.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("latency")]
    public Latency2? Latency { get; init; }

    /// <summary>
    /// The order in which the videos of the event appear within the event's playlist.
    /// <para>
    /// Option descriptions:
    ///  * <c>added_first</c> - The most recently added videos appear first.
    ///  * <c>added_last</c> - The most recently added videos appear last.
    ///  * <c>alphabetical</c> - The videos appear in alphabetical order.
    ///  * <c>arranged</c> - The videos appear in the order in which the user has arranged them.
    ///  * <c>comments</c> - The videos appear in order of number of comments.
    ///  * <c>duration</c> - The videos appear in order of duration.
    ///  * <c>likes</c> - The videos appear in order of number of likes.
    ///  * <c>newest</c> - The newest videos appear first.
    ///  * <c>oldest</c> - The oldest videos appear first.
    ///  * <c>plays</c> - The videos appear in order of number of plays.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("playlist_sort")]
    public PlaylistSort2? PlaylistSort { get; init; }

    /// <summary>
    /// The preferred streaming method.
    /// <para>
    /// Option descriptions:
    ///  * <c>browser</c> - Stream in the browser.
    ///  * <c>encoder</c> - Stream by the encoder.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("preferred_stream_method")]
    public PreferredStreamMethod? PreferredStreamMethod { get; init; }

    /// <summary>
    /// Information about the time or times that the event is expected to be live.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("schedule")]
    public Schedule? Schedule { get; init; }

    /// <summary>
    /// Whether the scheduled playback feature is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("scheduled_playback")]
    public bool? ScheduledPlayback { get; init; }

    /// <summary>
    /// Whether SRT encryption is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("srt_encryption_enabled")]
    public bool? SrtEncryptionEnabled { get; init; }

    /// <summary>
    /// The description of the next video to be streamed to the event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("stream_description")]
    public string? StreamDescription { get; init; }

    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("stream_embed")]
    public StreamEmbed? StreamEmbed { get; init; }

    /// <summary>
    /// The stream mode of the event.
    /// <para>
    /// Option descriptions:
    ///  * <c>live</c> - The stream is live playback.
    ///  * <c>record</c> - The stream is in record mode.
    ///  * <c>simulive</c> - The stream is scheduled media playback.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("stream_mode")]
    public StreamMode? StreamMode { get; init; }

    /// <summary>
    /// The password when <b>stream_privacy.view</b> is <c>password</c>. Anyone with the password can view the videos generated by streaming to the event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("stream_password")]
    public string? StreamPassword { get; init; }

    /// <summary>
    /// The privacy settings of the event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("stream_privacy")]
    public StreamPrivacy2? StreamPrivacy { get; init; }

    /// <summary>
    /// The title of the next video to be streamed to the event. This parameter is required when <b>automatically_title_stream</b> is <c>false</c>.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("stream_title")]
    public string? StreamTitle { get; init; }

    /// <summary>
    /// Whether the featuring for automatically stopping the live stream is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("streaming_auto_stop")]
    public bool? StreamingAutoStop { get; init; }

    /// <summary>
    /// The time zone used in resolving the timestamps that are included in automatically generated video titles.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("time_zone")]
    public string? TimeZone { get; init; }

    /// <summary>
    /// The title of the event. If <b>automatically_title_stream</b> is <c>true</c>, this value is the base title for videos created by streaming to this event.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>
    /// Whether the feature for 24/7 streaming is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("unlimited_duration")]
    public bool? UnlimitedDuration { get; init; }
}
