using System.Collections.Generic;
using System.Text.Json.Serialization;
using Vimeo.Core.Models;
using Vimeo.Models.Enums;

namespace Vimeo.Models;

public record RecurringEvent
{
    /// <summary>
    /// Information about the associated showcase.
    /// </summary>
    [JsonPropertyName("album")]
    public required Album2? Album { get; init; }

    /// <summary>
    /// Whether the share link for the videos generated by streaming to the event is usable.
    /// </summary>
    [JsonPropertyName("allow_share_link")]
    public required bool AllowShareLink { get; init; }

    /// <summary>
    /// An array of privacy settings supported for this event and the requesting user.
    /// </summary>
    [JsonPropertyName("allowed_privacies")]
    public required IReadOnlyList<string> AllowedPrivacies { get; init; }

    /// <summary>
    /// The OAuth app that created the event, when created through an OAuth app (e.g. StreamYard). <c>null</c> for events created natively in Vimeo.
    /// </summary>
    [JsonPropertyName("app")]
    public required ApiApp? App { get; init; }

    /// <summary>
    /// Whether the automated closed captions feature is enabled.
    /// </summary>
    [JsonPropertyName("auto_cc_enabled")]
    public required bool? AutoCcEnabled { get; init; }

    /// <summary>
    /// A comma-separated list of keywords for enhancing the speech detection of automated closed captions.
    /// </summary>
    [JsonPropertyName("auto_cc_keywords")]
    public required string? AutoCcKeywords { get; init; }

    /// <summary>
    /// The language of the automated closed captions.
    /// <para>
    /// Option descriptions:
    ///  * <c>af</c> - The language is Afrikaans.
    ///  * <c>am</c> - The language is Amharic.
    ///  * <c>ar</c> - The language is Arabic.
    ///  * <c>as</c> - The language is Assamese.
    ///  * <c>ast</c> - The language is Asturian.
    ///  * <c>az</c> - The language is Azerbaijani.
    ///  * <c>be</c> - The language is Belarusian.
    ///  * <c>bg</c> - The language is Bulgarian.
    ///  * <c>bn</c> - The language is Bengali.
    ///  * <c>bs</c> - The language is Bosnian.
    ///  * <c>ca</c> - The language is Catalan.
    ///  * <c>ceb</c> - The language is Cebuano.
    ///  * <c>cs</c> - The language is Czech.
    ///  * <c>cy</c> - The language is Welsh.
    ///  * <c>da</c> - The language is Danish.
    ///  * <c>de</c> - The language is German.
    ///  * <c>el</c> - The language is Greek.
    ///  * <c>en</c> - The language is English.
    ///  * <c>es</c> - The language is Spanish.
    ///  * <c>et</c> - The language is Estonian.
    ///  * <c>fa</c> - The language is Persian.
    ///  * <c>ff</c> - The language is Fulah.
    ///  * <c>fi</c> - The language is Finnish.
    ///  * <c>fil</c> - The language is Filipino.
    ///  * <c>fr</c> - The language is French.
    ///  * <c>ga</c> - The language is Irish.
    ///  * <c>gl</c> - The language is Galician.
    ///  * <c>gu</c> - The language is Gujarati.
    ///  * <c>ha</c> - The language is Hausa.
    ///  * <c>he</c> - The language is Hebrew.
    ///  * <c>hi</c> - The language is Hindi.
    ///  * <c>hr</c> - The language is Croatian.
    ///  * <c>hu</c> - The language is Hungarian.
    ///  * <c>hy</c> - The language is Armenian.
    ///  * <c>id</c> - The language is Indonesian.
    ///  * <c>ig</c> - The language is Igbo.
    ///  * <c>is</c> - The language is Icelandic.
    ///  * <c>it</c> - The language is Italian.
    ///  * <c>ja</c> - The language is Japanese.
    ///  * <c>jv</c> - The language is Javanese.
    ///  * <c>ka</c> - The language is Georgian.
    ///  * <c>kea</c> - The language is Kabuverdianu.
    ///  * <c>kk</c> - The language is Kazakh.
    ///  * <c>km</c> - The language is Khmer.
    ///  * <c>kn</c> - The language is Kannada.
    ///  * <c>ko</c> - The language is Korean.
    ///  * <c>ku</c> - The language is Kurdish.
    ///  * <c>ky</c> - The language is Kyrgyz.
    ///  * <c>lb</c> - The language is Luxembourgish.
    ///  * <c>lg</c> - The language is Ganda.
    ///  * <c>ln</c> - The language is Lingala.
    ///  * <c>lo</c> - The language is Lao.
    ///  * <c>lt</c> - The language is Lithuanian.
    ///  * <c>luo</c> - The language is Luo.
    ///  * <c>lv</c> - The language is Latvian.
    ///  * <c>mi</c> - The language is Maori.
    ///  * <c>mk</c> - The language is Macedonian.
    ///  * <c>ml</c> - The language is Malayalam.
    ///  * <c>mn</c> - The language is Mongolian.
    ///  * <c>mr</c> - The language is Marathi.
    ///  * <c>ms</c> - The language is Malay.
    ///  * <c>mt</c> - The language is Maltese.
    ///  * <c>my</c> - The language is Burmese.
    ///  * <c>ne</c> - The language is Nepali.
    ///  * <c>nl</c> - The language is Dutch.
    ///  * <c>no</c> - The language is Norwegian.
    ///  * <c>nso</c> - The language is Northern Sotho.
    ///  * <c>ny</c> - The language is Nyanja.
    ///  * <c>oc</c> - The language is Occitan.
    ///  * <c>or</c> - The language is Odia.
    ///  * <c>pa</c> - The language is Punjabi.
    ///  * <c>pl</c> - The language is Polish.
    ///  * <c>ps</c> - The language is Pashto.
    ///  * <c>pt</c> - The language is Portuguese.
    ///  * <c>ro</c> - The language is Romanian.
    ///  * <c>ru</c> - The language is Russian.
    ///  * <c>sd</c> - The language is Sindhi.
    ///  * <c>sk</c> - The language is Slovak.
    ///  * <c>sl</c> - The language is Slovenian.
    ///  * <c>sn</c> - The language is Shona.
    ///  * <c>so</c> - The language is Somali.
    ///  * <c>sr</c> - The language is Serbian.
    ///  * <c>sv</c> - The language is Swedish.
    ///  * <c>sw</c> - The language is Swahili.
    ///  * <c>ta</c> - The language is Tamil.
    ///  * <c>te</c> - The language is Telugu.
    ///  * <c>tg</c> - The language is Tajik.
    ///  * <c>th</c> - The language is Thai.
    ///  * <c>tr</c> - The language is Turkish.
    ///  * <c>uk</c> - The language is Ukrainian.
    ///  * <c>umb</c> - The language is Umbundu.
    ///  * <c>ur</c> - The language is Urdu.
    ///  * <c>uz</c> - The language is Uzbek.
    ///  * <c>vi</c> - The language is Vietnamese.
    ///  * <c>wo</c> - The language is Wolof.
    ///  * <c>xh</c> - The language is Xhosa.
    ///  * <c>zh</c> - The language is Chinese.
    ///  * <c>zh-HK</c> - The language is Cantonese (Hong Kong).
    ///  * <c>zu</c> - The language is Zulu.
    /// </para>
    /// </summary>
    [JsonPropertyName("auto_cc_language")]
    public required AutoCcLanguage? AutoCcLanguage { get; init; }

    /// <summary>
    /// The maximum seconds for automated closed captions (legacy, for users not yet on AI-credit billing).
    /// </summary>
    [JsonPropertyName("auto_cc_limit")]
    public required double? AutoCcLimit { get; init; }

    /// <summary>
    /// The seconds remaining for automated closed captions (legacy, for users not yet on AI-credit billing).
    /// </summary>
    [JsonPropertyName("auto_cc_remaining")]
    public required double? AutoCcRemaining { get; init; }

    /// <summary>
    /// Whether automated caption translations are enabled.
    /// </summary>
    [JsonPropertyName("auto_cc_translation_enabled")]
    public required bool? AutoCcTranslationEnabled { get; init; }

    /// <summary>
    /// The list of language codes for caption translations.
    /// </summary>
    [JsonPropertyName("auto_cc_translation_languages")]
    public required IReadOnlyList<string?> AutoCcTranslationLanguages { get; init; }

    /// <summary>
    /// When the value of this field is <c>true</c>, the title for the next video in the event is generated based on the time of the stream and the <b>title</b> field of the event.
    /// </summary>
    [JsonPropertyName("automatically_title_stream")]
    public required bool AutomaticallyTitleStream { get; init; }

    /// <summary>
    /// The backup stream key used in conjunction with the RTMP and RTMPS links.
    /// </summary>
    [JsonPropertyName("backup_stream_key")]
    public required string? BackupStreamKey { get; init; }

    /// <summary>
    /// Whether to display live chat on the event page on Vimeo.
    /// </summary>
    [JsonPropertyName("chat_enabled")]
    public required bool ChatEnabled { get; init; }

    /// <summary>
    /// The time in ISO 8601 format when the event was completed.
    /// </summary>
    [JsonPropertyName("completed_on")]
    public required string CompletedOn { get; init; }

    /// <summary>
    /// The event's granular content ratings.
    /// <para>
    /// Option descriptions:
    ///  * <c>advertisement</c> - The event contains advertisements.
    ///  * <c>drugs</c> - The event contains drug or alcohol use.
    ///  * <c>language</c> - The event contains profanity or sexually suggestive content.
    ///  * <c>nudity</c> - The event contains nudity.
    ///  * <c>safe</c> - The event is safe for all audiences.
    ///  * <c>unrated</c> - The event hasn't been rated.
    ///  * <c>violence</c> - The event contains violence.
    /// </para>
    /// </summary>
    [JsonPropertyName("content_rating")]
    public required ContentRating2 ContentRating { get; init; }

    /// <summary>
    /// The time in ISO 8601 format when the event was created.
    /// </summary>
    [JsonPropertyName("created_time")]
    public required string CreatedTime { get; init; }

    /// <summary>
    /// Whether the feature for disabling auto-archiving is enabled.
    /// </summary>
    [JsonPropertyName("disable_auto_archiving")]
    public required bool DisableAutoArchiving { get; init; }

    /// <summary>
    /// Whether the DVR feature is enabled.
    /// </summary>
    [JsonPropertyName("dvr")]
    public required bool Dvr { get; init; }

    /// <summary>
    /// Information about the event owner's email quota.
    /// </summary>
    [JsonPropertyName("email_quota")]
    public required EmailQuota EmailQuota { get; init; }

    /// <summary>
    /// The event's embed data.
    /// </summary>
    [JsonPropertyName("embed")]
    public required Embed3 Embed { get; init; }

    /// <summary>
    /// The event type.
    /// </summary>
    [JsonPropertyName("event_type")]
    public required string EventType { get; init; }

    /// <summary>
    /// Whether the event was created from a showcase.
    /// </summary>
    [JsonPropertyName("from_showcase")]
    public required bool FromShowcase { get; init; }

    /// <summary>
    /// Whether the event was created from a webinar.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("from_webinar")]
    public bool? FromWebinar { get; init; }

    /// <summary>
    /// Whether the event has forced lead capture form enabled.
    /// </summary>
    [JsonPropertyName("has_forced_lead_capture_form")]
    public required bool HasForcedLeadCaptureForm { get; init; }

    /// <summary>
    /// The first video to be played in the playlist.
    /// </summary>
    [JsonPropertyName("head_clip")]
    public required object? HeadClip { get; init; }

    /// <summary>
    /// The settings for the interaction tools.
    /// </summary>
    [JsonPropertyName("interaction_tools_settings")]
    public required IReadOnlyList<InteractionToolsSetting?> InteractionToolsSettings { get; init; }

    /// <summary>
    /// Whether the current user has starred this event.
    /// </summary>
    [JsonPropertyName("is_starred_by_cur_user")]
    public required bool IsStarredByCurUser { get; init; }

    /// <summary>
    /// The navbar logo configuration of the event landing page, or <c>null</c> when the event was never configured (default rendering).
    /// </summary>
    [JsonPropertyName("landing_page_logo")]
    public required LandingPageLogo? LandingPageLogo { get; init; }

    /// <summary>
    /// The type of latency.
    /// <para>
    /// Option descriptions:
    ///  * <c>fail-safe</c> - The latency is in the failsafe range, with a delay of 60-75 seconds.
    ///  * <c>low</c> - The latency is low, with a delay of 5-7 seconds.
    ///  * <c>standard</c> - The latency is standard, with a delay of 15-20 seconds.
    /// </para>
    /// </summary>
    [JsonPropertyName("latency")]
    public required Latency Latency { get; init; }

    /// <summary>
    /// The unique ID for the registered viewer.
    /// </summary>
    [JsonPropertyName("lead_uuid")]
    public required string LeadUuid { get; init; }

    /// <summary>
    /// The URI to access the event on Vimeo.
    /// </summary>
    [JsonPropertyName("link")]
    public required string Link { get; init; }

    /// <summary>
    /// A list of videos belonging to the event, including their video IDs and dates streamed.
    /// </summary>
    [JsonPropertyName("live_clips")]
    public required IReadOnlyList<string> LiveClips { get; init; }

    /// <summary>
    /// _This field is deprecated in favor of the following method: <see href="https://developer.vimeo.com/api/reference/live#get_one_time_event_destinations">Get all the destinations of a one-time event</see>._
    /// </summary>
    [JsonPropertyName("live_destinations")]
    public required IReadOnlyList<string?> LiveDestinations { get; init; }

    /// <summary>
    /// Metadata about the event.
    /// </summary>
    [JsonPropertyName("metadata")]
    public required Metadata15 Metadata { get; init; }

    /// <summary>
    /// The date in ISO 8601 format on which the next occurrence of the event is expected to be live.
    /// </summary>
    [JsonPropertyName("next_occurrence_time")]
    public required string? NextOccurrenceTime { get; init; }

    /// <summary>
    /// Information about the folder that contains the event.
    /// </summary>
    [JsonPropertyName("parent_folder")]
    public required Project? ParentFolder { get; init; }

    /// <summary>
    /// The active thumbnail image of the event.
    /// </summary>
    [JsonPropertyName("pictures")]
    public required Picture Pictures { get; init; }

    /// <summary>
    /// The order in which the videos inside the event appear in the playlist.
    /// <para>
    /// Option descriptions:
    ///  * <c>added_first</c> - The videos appear according to when they were added to the event, with the most recently added first.
    ///  * <c>added_last</c> - The videos appear according to when they were added to the event, with the most recently added last.
    ///  * <c>alphabetical</c> - The videos appear alphabetically by their title.
    ///  * <c>arranged</c> - The videos appear as arranged by the owner of the event.
    ///  * <c>comments</c> - The videos appear according to their number of comments.
    ///  * <c>duration</c> - The videos appear in order of duration.
    ///  * <c>likes</c> - The videos appear according to their number of likes.
    ///  * <c>newest</c> - The videos appear in chronological order, with the newest first.
    ///  * <c>oldest</c> - The videos appear in chronological order, with the oldest first.
    ///  * <c>plays</c> - The videos appear according to their number of plays.
    /// </para>
    /// </summary>
    [JsonPropertyName("playlist_sort")]
    public required PlaylistSort PlaylistSort { get; init; }

    /// <summary>
    /// The preferred streaming method.
    /// <para>
    /// Option descriptions:
    ///  * <c>browser</c> - Stream in the browser.
    ///  * <c>encoder</c> - Stream by the encoder.
    /// </para>
    /// </summary>
    [JsonPropertyName("preferred_stream_method")]
    public required PreferredStreamMethod PreferredStreamMethod { get; init; }

    /// <summary>
    /// On-demand recordings of the event's past streams.
    /// </summary>
    [JsonPropertyName("recordings")]
    public required IReadOnlyList<Recording> Recordings { get; init; }

    /// <summary>
    /// The upstream RTMP link. Send your live content to this link to create a live video on the event.
    /// </summary>
    [JsonPropertyName("rtmp_link")]
    public required string? RtmpLink { get; init; }

    /// <summary>
    /// Whether to preview the RTMP stream before the event goes live.
    /// </summary>
    [JsonPropertyName("rtmp_preview")]
    public required bool RtmpPreview { get; init; }

    /// <summary>
    /// The upstream RTMPS link. Send your live content to this link to create a live video on the event.
    /// </summary>
    [JsonPropertyName("rtmps_link")]
    public required string? RtmpsLink { get; init; }

    /// <summary>
    /// The description of the time or times that the event is expected to be live.
    /// </summary>
    [JsonPropertyName("schedule")]
    public required EventSchedule Schedule { get; init; }

    /// <summary>
    /// Whether the scheduled playback feature is enabled.
    /// </summary>
    [JsonPropertyName("scheduled_playback")]
    public required bool ScheduledPlayback { get; init; }

    /// <summary>
    /// The URI to access the event settings on Vimeo.
    /// </summary>
    [JsonPropertyName("settings_link")]
    public required string SettingsLink { get; init; }

    /// <summary>
    /// Whether SRT encryption is enabled.
    /// </summary>
    [JsonPropertyName("srt_encryption_enabled")]
    public required bool SrtEncryptionEnabled { get; init; }

    /// <summary>
    /// The upstream SRT link. To create a live video on the event, send your live content to this link.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("srt_link")]
    public string? SrtLink { get; init; }

    /// <summary>
    /// The secret key used in SRT streaming to encrypt data for secure transmission.
    /// </summary>
    [JsonPropertyName("srt_passphrase")]
    public required string? SrtPassphrase { get; init; }

    /// <summary>
    /// The status of the event.
    /// <para>
    /// Option descriptions:
    ///  * <c>ended</c> - The user ended the event.
    ///  * <c>started</c> - The user started the event.
    /// </para>
    /// </summary>
    [JsonPropertyName("status")]
    public required Status13? Status { get; init; }

    /// <summary>
    /// The description of the next video streamed to the event.
    /// </summary>
    [JsonPropertyName("stream_description")]
    public required string? StreamDescription { get; init; }

    /// <summary>
    /// The stream key used in conjunction with the RTMP and RTMPS links.
    /// </summary>
    [JsonPropertyName("stream_key")]
    public required string? StreamKey { get; init; }

    /// <summary>
    /// The stream mode of the event.
    /// <para>
    /// Option descriptions:
    ///  * <c>live</c> - The stream is live playback.
    ///  * <c>record</c> - The stream is in record mode.
    ///  * <c>simulive</c> - The stream is scheduled media playback.
    /// </para>
    /// </summary>
    [JsonPropertyName("stream_mode")]
    public required StreamMode StreamMode { get; init; }

    /// <summary>
    /// The password that anyone can use to access the videos generated by streaming to the event.
    /// </summary>
    [JsonPropertyName("stream_password")]
    public required string? StreamPassword { get; init; }

    /// <summary>
    /// The initial privacy settings of videos generated by streaming to the event as well as the embed privacy of the entire collection.
    /// </summary>
    [JsonPropertyName("stream_privacy")]
    public required StreamPrivacy StreamPrivacy { get; init; }

    /// <summary>
    /// The title of the next video streamed to the event. This field applies only when <b>automatically_title_stream</b> is <c>false</c>.
    /// </summary>
    [JsonPropertyName("stream_title")]
    public required string StreamTitle { get; init; }

    /// <summary>
    /// The event's video. An event always has a video, which is either in a pre-live state (ready to be streamed to) or in a live state (which is currently being streamed to).
    /// </summary>
    [JsonPropertyName("streamable_clip")]
    public required object? StreamableClip { get; init; }

    /// <summary>
    /// Whether the feature for automatically stopping the live stream is enabled.
    /// </summary>
    [JsonPropertyName("streaming_auto_stop")]
    public required bool StreamingAutoStop { get; init; }

    /// <summary>
    /// The time zone used in resolving the timestamps included in auto-generated video titles.
    /// </summary>
    [JsonPropertyName("time_zone")]
    public required string TimeZone { get; init; }

    /// <summary>
    /// The title of the event. This field is also optionally used as the base title for videos created by streaming to the event.
    /// </summary>
    [JsonPropertyName("title")]
    public required string Title { get; init; }

    /// <summary>
    /// Whether to ignore the time limit of the automated closed captions feature.
    /// </summary>
    [JsonPropertyName("unlimited_auto_cc")]
    public required bool? UnlimitedAutoCc { get; init; }

    /// <summary>
    /// Whether the feature for 24/7 streaming is enabled.
    /// </summary>
    [JsonPropertyName("unlimited_duration")]
    public required bool UnlimitedDuration { get; init; }

    /// <summary>
    /// The event's canonical relative URI.
    /// </summary>
    [JsonPropertyName("uri")]
    public required string Uri { get; init; }

    /// <summary>
    /// The owner of the event.
    /// </summary>
    [JsonPropertyName("user")]
    public required User User { get; init; }

    /// <summary>
    /// The ID of the associated Venues API service database object. If this field has no value, there is no associated Venues object.
    /// </summary>
    [JsonPropertyName("venue_uuid")]
    public required string? VenueUuid { get; init; }

    /// <summary>
    /// The URI to access the event on Vimeo with or without an unlisted hash.
    /// </summary>
    [JsonPropertyName("view_link")]
    public required string ViewLink { get; init; }

    /// <summary>
    /// Information about the associated webinar.
    /// </summary>
    [JsonPropertyName("webinar")]
    public required IReadOnlyList<string?> Webinar { get; init; }

    /// <summary>
    /// The permitted domains for a video.
    /// </summary>
    [JsonPropertyName("whitelisted_domains")]
    public required IReadOnlyList<Domain?> WhitelistedDomains { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
