using System.Collections.Generic;
using System.Text.Json.Serialization;
using Vimeo.Core.Models;
using Vimeo.Models.Enums;

namespace Vimeo.Models;

public record Segment
{
    /// <summary>
    /// Whether the segment is autogenerated.
    /// </summary>
    [JsonPropertyName("autogenerated")]
    public required bool Autogenerated { get; init; }

    /// <summary>
    /// The cue end timestamp in milliseconds from the start of the video.
    /// </summary>
    [JsonPropertyName("cue_end")]
    public required double CueEnd { get; init; }

    /// <summary>
    /// The cue start timestamp in milliseconds from the start of the video.
    /// </summary>
    [JsonPropertyName("cue_start")]
    public required double CueStart { get; init; }

    /// <summary>
    /// Whether the segment is enabled.
    /// </summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }

    /// <summary>
    /// The segment identifier.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// The type of caption that the segment originates from.
    /// <para>
    /// Option descriptions:
    ///  * <c>captions</c> - The segment originates from a captions file.
    ///  * <c>subtitles</c> - The segment originates from a captions and subtitles file.
    /// </para>
    /// </summary>
    [JsonPropertyName("kind")]
    public required Kind1 Kind { get; init; }

    /// <summary>
    /// The language of the segment.
    /// </summary>
    [JsonPropertyName("language")]
    public required string Language { get; init; }

    /// <summary>
    /// The line data for the segment.
    /// </summary>
    [JsonPropertyName("lines")]
    public required IReadOnlyList<SegmentLine> Lines { get; init; }

    /// <summary>
    /// The speaker identifier.
    /// </summary>
    [JsonPropertyName("speaker")]
    public required string? Speaker { get; init; }

    /// <summary>
    /// The relative URI of the text track that the segment comes from.
    /// </summary>
    [JsonPropertyName("text_track_uri")]
    public required string TextTrackUri { get; init; }

    /// <summary>
    /// The translation metadata of the segment.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("translation_metadata")]
    public SegmentTranslationMetadata? TranslationMetadata { get; init; }

    /// <summary>
    /// The canonical relative URI of the segment's video.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("video_uri")]
    public string? VideoUri { get; init; }

    /// <summary>
    /// The word data for the segment.
    /// </summary>
    [JsonPropertyName("words")]
    public required IReadOnlyList<SegmentWords> Words { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
