using System.Text.Json.Serialization;
using VimeoApi.Core.Models;
using VimeoApi.Models.Enums;

namespace VimeoApi.Models;

/// <summary>
/// The initial privacy settings of videos generated by streaming to the event as well as the embed privacy of the entire collection.
/// </summary>
public record StreamPrivacy
{
    /// <summary>
    /// The event's embed permission setting.
    /// <para>
    /// Option descriptions:
    ///  * <c>private</c> - The event can't be embedded on any domain.
    ///  * <c>public</c> - The event can be embedded on any domain.
    ///  * <c>whitelist</c> - The event can be embedded on permitted domains only.
    /// </para>
    /// </summary>
    [JsonPropertyName("embed")]
    public required Embed4 Embed { get; init; }

    /// <summary>
    /// The hash for unlisted events.
    /// </summary>
    [JsonPropertyName("unlisted_hash")]
    public required string? UnlistedHash { get; init; }

    /// <summary>
    /// The general privacy setting for generated videos and the embed privacy of the entire collection.
    /// <para>
    /// Option descriptions:
    ///  * <c>anybody</c> - Anyone can access the videos. This privacy setting appears as <c>Public</c> on the Vimeo front end.
    ///  * <c>embed_only</c> - The videos don't appear on Vimeo, but they can be embedded elsewhere.
    ///  * <c>nobody</c> - Only the event owner can access the videos. This privacy setting appears as <c>Private</c> on the Vimeo front end.
    ///  * <c>password</c> - Only those with the password can access the videos.
    ///  * <c>team</c> - Anyone on this team can access the videos. This privacy setting appears as <c>Company only</c> on the Vimeo front end.
    ///  * <c>unlisted</c> - Only those with the private link can access the videos.
    /// </para>
    /// </summary>
    [JsonPropertyName("view")]
    public required View7 View { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
