using System.Text.Json.Serialization;
using Vimeo.Core.Models;
using Vimeo.Models.Enums;

namespace Vimeo.Models;

/// <summary>
/// The privacy settings of the event.
/// </summary>
public record StreamPrivacy2
{
    /// <summary>
    /// The initial privacy of the videos generated by streaming to the event as well as the embed privacy of the entire collection.
    /// <para>
    /// Option descriptions:
    ///  * <c>anybody</c> - Anyone can access the event. This privacy setting appears as <c>Public</c> on the Vimeo front end.
    ///  * <c>embed_only</c> - The event doesn't appear on Vimeo, but it can be embedded on other sites.
    ///  * <c>nobody</c> - No one except the owner can access the event. This privacy setting appears as <c>Private</c> on the Vimeo front end.
    ///  * <c>password</c> - Only those with the password can access the event.
    ///  * <c>team</c> - Anyone on this team can access the event. This privacy setting appears as <c>Company only</c> on the Vimeo front end.
    ///  * <c>unlisted</c> - Only those with the private link can access the event.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("view")]
    public View9? View { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
