using System.Text.Json.Serialization;

namespace VimeoApi.Models;

public record TranscriptMetadata
{
    /// <summary>
    /// Whether the transcript was automatically generated using AI.
    /// </summary>
    [JsonPropertyName("autogenerated")]
    public required bool Autogenerated { get; init; }

    /// <summary>
    /// The ID of the video.
    /// </summary>
    [JsonPropertyName("clip_id")]
    public required double ClipId { get; init; }

    /// <summary>
    /// The ID of the container.
    /// </summary>
    [JsonPropertyName("container_id")]
    public required string ContainerId { get; init; }

    /// <summary>
    /// Whether the transcript has been marked as deleted.
    /// </summary>
    [JsonPropertyName("deleted")]
    public required bool Deleted { get; init; }

    /// <summary>
    /// Whether the transcript is enabled.
    /// </summary>
    [JsonPropertyName("enabled")]
    public required bool Enabled { get; init; }

    /// <summary>
    /// The ID of the transcript.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// The kind of transcript. The value of this field can be <c>captions</c> for caption transcripts or <c>subtitles</c> for subtitle transcripts.
    /// </summary>
    [JsonPropertyName("kind")]
    public required string Kind { get; init; }

    /// <summary>
    /// The language in which the transcript appears.
    /// </summary>
    [JsonPropertyName("language")]
    public required string Language { get; init; }

    /// <summary>
    /// The total number of speakers in the transcript.
    /// </summary>
    [JsonPropertyName("speaker_count")]
    public required double SpeakerCount { get; init; }

    /// <summary>
    /// The ID of the text track.
    /// </summary>
    [JsonPropertyName("texttrack_id")]
    public required double TexttrackId { get; init; }

    /// <summary>
    /// The UUID of the transcript status.
    /// </summary>
    [JsonPropertyName("transcript_status_uuid")]
    public required string TranscriptStatusUuid { get; init; }

    /// <summary>
    /// The total number of words in the transcript.
    /// </summary>
    [JsonPropertyName("word_count")]
    public required double WordCount { get; init; }
}
