using System.Text.Json.Serialization;
using VimeoApi.Models.Enums;

namespace VimeoApi.Models;

public record VideosVersionsAudiotracksRequest
{
    /// <summary>
    /// Whether the audio track is enabled.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("active")]
    public bool? Active { get; init; }

    /// <summary>
    /// The language of the audio track. For a full list of supported languages, use the <see href="https://developer.vimeo.com/api/reference/videos#get_languages"><c>/languages?filter=audiotracks</c></see> method.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("language_code")]
    public string? LanguageCode { get; init; }

    /// <summary>
    /// The origin of the audio track.
    /// <para>
    /// Option descriptions:
    ///  * <c>ai_generated</c> - The audio track is generated by AI.
    ///  * <c>user_uploaded</c> - The audio track is uploaded by a user.
    ///  * <c>user_uploaded_and_ai_generated</c> - The audio track is uploaded by a user and contains AI content.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("provenance")]
    public Provenance2? Provenance { get; init; }

    /// <summary>
    /// The type of audio track.
    /// <para>
    /// Option descriptions:
    ///  * <c>commentary</c> - The audio track is the commentary type.
    ///  * <c>descriptive</c> - The audio track is the descriptive type.
    ///  * <c>main</c> - The audio track is the main type.
    /// </para>
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("type")]
    public Type57? Type { get; init; }

    [JsonPropertyName("upload")]
    public required Upload5 Upload { get; init; }
}
