using System.Text.Json.Serialization;
using VimeoApi.Core.Models;
using VimeoApi.Models.Enums;

namespace VimeoApi.Models;

public record VideosTexttracksRequest
{
    /// <summary>
    /// Whether the current text track is the *active text track,* or the one that appears in the player. Only one text track per language and type can be active.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("active")]
    public bool? Active { get; init; }

    /// <summary>
    /// Whether the text track was uploaded automatically by the Seshat audio annotation management platform.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("is_auto_generated")]
    public bool? IsAutoGenerated { get; init; }

    /// <summary>
    /// Whether the text track was uploaded by the Seshat audio annotation management platform after the user edited their transcript.
    /// </summary>
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    [JsonPropertyName("is_edited")]
    public bool? IsEdited { get; init; }

    /// <summary>
    /// The language of the text track. For a full list of supported languages, use the <see href="https://developer.vimeo.com/api/reference/videos#get_languages"><c>/languages?filter=texttracks</c></see> endpoint.
    /// </summary>
    [JsonPropertyName("language")]
    public required string Language { get; init; }

    /// <summary>
    /// The name of the text track.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// The type of text track.
    /// <para>
    /// Option descriptions:
    ///  * <c>captions</c> - The text track is the captions type.
    ///  * <c>chapters</c> - The text track is the chapters type.
    ///  * <c>descriptions</c> - The text track is the descriptions type.
    ///  * <c>metadata</c> - The text track is the metadata type.
    ///  * <c>subtitles</c> - The text track is the subtitles type.
    /// </para>
    /// </summary>
    [JsonPropertyName("type")]
    public required Type25 Type { get; init; }

    [JsonExtensionData]
    public AdditionalProperties AdditionalProperties { get; init; } = [];
}
